In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
a.itemsize

4

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6,7,8])

In [12]:
b

array([6, 7, 8])

In [13]:
type(b)

numpy.ndarray

In [15]:
a=np.array([2,3,4])

In [16]:
a

array([2, 3, 4])

In [24]:
b = np.array ([2,3,4]), ([5,6,7])

In [22]:
b

(array([2, 3, 4]), [5, 6, 7])

In [25]:
np.ones((2,3,4,5),dtype=np.int16)

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int16)

In [26]:
np.empty((2,5))

array([[2.41907520e-312, 1.29441743e-312, 2.37663529e-312,
        2.58883487e-312, 2.41907520e-312],
       [8.48798317e-313, 1.12465777e-312, 1.12465777e-312,
        8.70018274e-313, 2.56765117e-312]])

In [28]:
np.arange(2,3,20)

array([2])

In [33]:
x = np.arange(12).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
c = np.arange(24).reshape(2,3,4)

In [35]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
z= np.array ([20,30,40,50])
y=np.arange(4)

In [43]:
y

array([0, 1, 2, 3])

In [41]:
x = z-y

In [44]:
x

array([20, 29, 38, 47])

In [45]:
y**2

array([0, 1, 4, 9], dtype=int32)

In [46]:
z<25

array([ True, False, False, False])

In [47]:
z>30

array([False, False,  True,  True])

In [49]:
a = np.array ([[1,1],
         [0,1]])
b = np.array ([[2,0],
               [3,4]])

In [50]:
a*b

array([[2, 0],
       [0, 4]])

In [51]:
a@b

array([[5, 4],
       [3, 4]])

In [52]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [55]:
x= np.rg.random ((2,3))

AttributeError: module 'numpy' has no attribute 'rg'